#!/bin/bash

dev_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
dev_dir="$( dirname "$dev_dir" )"

set -e
set -o pipefail

docker run "$@" -it --net=host -v  /tmp/.X11-unix:/tmp/.X11-unix \
 -v /dev:/dev \
 -v $HOME/2023RobotCode:/home/ubuntu/.2023RobotCode.readonly \
 -v $HOME/minifrc:/home/ubuntu/minifrc \
 --ipc=host \
 --shm-size=8G \
 -e DISPLAY=$DISPLAY -e NVIDIA_DRIVER_CAPABILITIES=all --privileged --user ubuntu zebramites2023 /bin/bash
